## NOTEBOOK 1 ##

**Goal:**
The Goal of this project is to Predict employee performance to help HR improve productivity

In [2]:
# Import all the libraries.
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore') 

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import  StandardScaler,LabelEncoder 
from sklearn.impute import SimpleImputer 
from sklearn.compose import ColumnTransformer 
from sklearn.pipeline import Pipeline 

from sklearn.linear_model import LogisticRegression 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier 
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.svm import SVC 
from xgboost import XGBClassifier 

from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,classification_report,confusion_matrix,roc_auc_score

In [3]:
import sys
sys.path.append(r'C:\Users\Lenovo\Downloads\Employee Performance')
from config import BASE, RAW_DATA, CLEANED, PREDICTIONS, MODEL
data = pd.read_excel(RAW_DATA)

In [4]:
# Check the data of first 5 rows
data.head()

,EmpNumber,Age,Gender,EducationBackground,MaritalStatus,EmpDepartment,EmpJobRole,BusinessTravelFrequency,DistanceFromHome,EmpEducationLevel,...,EmpRelationshipSatisfaction,TotalWorkExperienceInYears,TrainingTimesLastYear,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition,PerformanceRating
0,E1001000,32,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,10,3,...,4,10,2,2,10,7,0,8,No,3
1,E1001006,47,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,14,4,...,4,20,2,3,7,7,1,7,No,3
2,E1001007,40,Male,Life Sciences,Married,Sales,Sales Executive,Travel_Frequently,5,4,...,3,20,2,3,18,13,1,12,No,4
3,E1001009,41,Male,Human Resources,Divorced,Human Resources,Manager,Travel_Rarely,10,4,...,2,23,2,2,21,6,12,6,No,3
4,E1001010,60,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,16,4,...,4,10,1,3,2,2,2,2,No,3

In [5]:
# Check the data of last 5 rows
data.tail()

,EmpNumber,Age,Gender,EducationBackground,MaritalStatus,EmpDepartment,EmpJobRole,BusinessTravelFrequency,DistanceFromHome,EmpEducationLevel,...,EmpRelationshipSatisfaction,TotalWorkExperienceInYears,TrainingTimesLastYear,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition,PerformanceRating
1195,E100992,27,Female,Medical,Divorced,Sales,Sales Executive,Travel_Frequently,3,1,...,2,6,3,3,6,5,0,4,No,4
1196,E100993,37,Male,Life Sciences,Single,Development,Senior Developer,Travel_Rarely,10,2,...,1,4,2,3,1,0,0,0,No,3
1197,E100994,50,Male,Medical,Married,Development,Senior Developer,Travel_Rarely,28,1,...,3,20,3,3,20,8,3,8,No,3
1198,E100995,34,Female,Medical,Single,Data Science,Data Scientist,Travel_Rarely,9,3,...,2,9,3,4,8,7,7,7,No,3
1199,E100998,24,Female,Life Sciences,Single,Sales,Sales Executive,Travel_Rarely,3,2,...,1,4,3,3,2,2,2,0,Yes,2

In [6]:
# Check the info of the data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 28 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   EmpNumber                     1200 non-null   object
 1   Age                           1200 non-null   int64
 2   Gender                        1200 non-null   object
 3   EducationBackground           1200 non-null   object
 4   MaritalStatus                 1200 non-null   object
 5   EmpDepartment                 1200 non-null   object
 6   EmpJobRole                    1200 non-null   object
 7   BusinessTravelFrequency       1200 non-null   object
 8   DistanceFromHome              1200 non-null   int64
 9   EmpEducationLevel             1200 non-null   int64
 10  EmpEnvironmentSatisfaction    1200 non-null   int64
 11  EmpHourlyRate                 1200 non-null   int64
 12  EmpJobInvolvement             1200 non-null   int64
 13  EmpJobLevel                   1200 non-null   int64
 14  EmpJobSatisfaction            1200 non-null   int64
 15  NumCompaniesWorked            1200 non-null   int64
 16  OverTime                      1200 non-null   object
 17  EmpLastSalaryHikePercent      1200 non-null   int64
 18  EmpRelationshipSatisfaction   1200 non-null   int64
 19  TotalWorkExperienceInYears    1200 non-null   int64
 20  TrainingTimesLastYear         1200 non-null   int64
 21  EmpWorkLifeBalance            1200 non-null   int64
 22  ExperienceYearsAtThisCompany  1200 non-null   int64
 23  ExperienceYearsInCurrentRole  1200 non-null   int64
 24  YearsSinceLastPromotion       1200 non-null   int64
 25  YearsWithCurrManager          1200 non-null   int64
 26  Attrition                     1200 non-null   object
 27  PerformanceRating             1200 non-null   int64
dtypes: int64(19), object(9)
memory usage: 262.6+ KB

In [7]:
# Check the column names are in readable format.
data.columns

Index(['EmpNumber', 'Age', 'Gender', 'EducationBackground', 'MaritalStatus',
       'EmpDepartment', 'EmpJobRole', 'BusinessTravelFrequency',
       'DistanceFromHome', 'EmpEducationLevel', 'EmpEnvironmentSatisfaction',
       'EmpHourlyRate', 'EmpJobInvolvement', 'EmpJobLevel',
       'EmpJobSatisfaction', 'NumCompaniesWorked', 'OverTime',
       'EmpLastSalaryHikePercent', 'EmpRelationshipSatisfaction',
       'TotalWorkExperienceInYears', 'TrainingTimesLastYear',
       'EmpWorkLifeBalance', 'ExperienceYearsAtThisCompany',
       'ExperienceYearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'Attrition', 'PerformanceRating'],
      dtype='object')

In [8]:
# Check for null values in data 
missing = data.isnull().sum() 
missing_per = (missing/len(data)) * 100 
missing_df = pd.DataFrame({'Missing Count':missing ,'Missing %':missing_per.round(2)}) 
print('Missing values Check') 
print(missing_df[missing_df['Missing Count'] > 0]) 
print(f'\n Total Missing Values:{missing.sum()}')

Missing values Check
Empty DataFrame
Columns: [Missing Count, Missing %]
Index: []

 Total Missing Values:0

In [9]:
# Check for duplicates in the data
data.duplicated().sum()

0

In [10]:
# Check the unique number of Employees
print(f'\n Unique Employee Numbers : {data['EmpNumber'].nunique()}/{len(data)}Total')

 Unique Employee Numbers : 1200/1200Total

In [11]:
# Check the statistical summary of the data
data.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,1200.0,36.918333,9.087289,18.0,30.0,36.0,43.0,60.0
DistanceFromHome,1200.0,9.165833,8.176636,1.0,2.0,7.0,14.0,29.0
EmpEducationLevel,1200.0,2.892500,1.044120,1.0,2.0,3.0,4.0,5.0
EmpEnvironmentSatisfaction,1200.0,2.715833,1.090599,1.0,2.0,3.0,4.0,4.0
EmpHourlyRate,1200.0,65.981667,20.211302,30.0,48.0,66.0,83.0,100.0
EmpJobInvolvement,1200.0,2.731667,0.707164,1.0,2.0,3.0,3.0,4.0
EmpJobLevel,1200.0,2.067500,1.107836,1.0,1.0,2.0,3.0,5.0
EmpJobSatisfaction,1200.0,2.732500,1.100888,1.0,2.0,3.0,4.0,4.0
NumCompaniesWorked,1200.0,2.665000,2.469384,0.0,1.0,2.0,4.0,9.0
EmpLastSalaryHikePercent,1200.0,15.222500,3.625918,11.0,12.0,14.0,18.0,25.0
EmpRelationshipSatisfaction,1200.0,2.725000,1.075642,1.0,2.0,3.0,4.0,4.0
TotalWorkExperienceInYears,1200.0,11.330000,7.797228,0.0,6.0,10.0,15.0,40.0
TrainingTimesLastYear,1200.0,2.785833,1.263446,0.0,2.0,3.0,3.0,6.0
EmpWorkLifeBalance,1200.0,2.744167,0.699374,1.0,2.0,3.0,3.0,4.0
ExperienceYearsAtThisCompany,1200.0,7.077500,6.236899,0.0,3.0,5.0,10.0,40.0
ExperienceYearsInCurrentRole,1200.0,4.291667,3.613744,0.0,2.0,3.0,7.0,18.0
YearsSinceLastPromotion,1200.0,2.194167,3.221560,0.0,0.0,1.0,3.0,15.0
YearsWithCurrManager,1200.0,4.105000,3.541576,0.0,2.0,3.0,7.0,17.0
PerformanceRating,1200.0,2.948333,0.518866,2.0,3.0,3.0,3.0,4.0

In [12]:
# Check the values counts of the target column
data['PerformanceRating'].value_counts()

PerformanceRating
3    874
2    194
4    132
Name: count, dtype: int64

In [13]:
# Identify the categorical and numerical columns 
categorical_cols = data.select_dtypes(include=['object']).columns.tolist() 
numerical_cols = data.select_dtypes(include=['int64','float64']).columns.tolist()  
# Remove that EmpNumber from numerical column because it is ID not useful for prediction 
numerical_cols = [c for c in numerical_cols if c != 'EmpNumber'] 
print(f'Categorical Columns: ({len(categorical_cols)}):{categorical_cols}') 
print(f'Numerical Columns : ({len(numerical_cols)}):{numerical_cols}')

Categorical Columns: (9):['EmpNumber', 'Gender', 'EducationBackground', 'MaritalStatus', 'EmpDepartment', 'EmpJobRole', 'BusinessTravelFrequency', 'OverTime', 'Attrition']
Numerical Columns : (19):['Age', 'DistanceFromHome', 'EmpEducationLevel', 'EmpEnvironmentSatisfaction', 'EmpHourlyRate', 'EmpJobInvolvement', 'EmpJobLevel', 'EmpJobSatisfaction', 'NumCompaniesWorked', 'EmpLastSalaryHikePercent', 'EmpRelationshipSatisfaction', 'TotalWorkExperienceInYears', 'TrainingTimesLastYear', 'EmpWorkLifeBalance', 'ExperienceYearsAtThisCompany', 'ExperienceYearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager', 'PerformanceRating']

In [14]:
# Check the distribution of all categorical columns 
for col in categorical_cols:
    print(data[col].value_counts())

EmpNumber
E1001000    1
E100346     1
E100342     1
E100341     1
E100340     1
           ..
E1001718    1
E1001717    1
E1001716    1
E1001713    1
E100998     1
Name: count, Length: 1200, dtype: int64
Gender
Male      725
Female    475
Name: count, dtype: int64
EducationBackground
Life Sciences       492
Medical             384
Marketing           137
Technical Degree    100
Other                66
Human Resources      21
Name: count, dtype: int64
MaritalStatus
Married     548
Single      384
Divorced    268
Name: count, dtype: int64
EmpDepartment
Sales                     373
Development               361
Research & Development    343
Human Resources            54
Finance                    49
Data Science               20
Name: count, dtype: int64
EmpJobRole
Sales Executive              270
Developer                    236
Manager R&D                   94
Research Scientist            77
Sales Representative          69
Laboratory Technician         64
Senior Developer              52
Manager                       51
Finance Manager               49
Human Resources               45
Technical Lead                38
Manufacturing Director        33
Healthcare Representative     33
Data Scientist                20
Research Director             19
Business Analyst              16
Senior Manager R&D            15
Delivery Manager              12
Technical Architect            7
Name: count, dtype: int64
BusinessTravelFrequency
Travel_Rarely        846
Travel_Frequently    222
Non-Travel           132
Name: count, dtype: int64
OverTime
No     847
Yes    353
Name: count, dtype: int64
Attrition
No     1022
Yes     178
Name: count, dtype: int64

In [15]:
# Target Variable Distribution 
target_counts = data['PerformanceRating'].value_counts().sort_index()
target_per = (target_counts / len(data) * 100).round(2) 
target_df = pd.DataFrame({
    'Count':target_counts,
    'Percentage':target_per,
    'Label':{2:'Low',3:'Good',4:'Excellent'}
})
print('Performance Rating Distribution')
print(target_df)

Performance Rating Distribution
   Count  Percentage      Label
2    194       16.17        Low
3    874       72.83       Good
4    132       11.00  Excellent

In [16]:
# Encode for categorical columns 
df_encoded = data.copy() 
label_encoders = {} 
for col in categorical_cols:
    if col == 'EmpNumber':
        continue 
    le = LabelEncoder() 
    df_encoded[col] = le.fit_transform(df_encoded[col])
    print(f'Encoded {col} : {dict(zip(le.classes_,le.transform(le.classes_)))}')

Encoded Gender : {'Female': 0, 'Male': 1}
Encoded EducationBackground : {'Human Resources': 0, 'Life Sciences': 1, 'Marketing': 2, 'Medical': 3, 'Other': 4, 'Technical Degree': 5}
Encoded MaritalStatus : {'Divorced': 0, 'Married': 1, 'Single': 2}
Encoded EmpDepartment : {'Data Science': 0, 'Development': 1, 'Finance': 2, 'Human Resources': 3, 'Research & Development': 4, 'Sales': 5}
Encoded EmpJobRole : {'Business Analyst': 0, 'Data Scientist': 1, 'Delivery Manager': 2, 'Developer': 3, 'Finance Manager': 4, 'Healthcare Representative': 5, 'Human Resources': 6, 'Laboratory Technician': 7, 'Manager': 8, 'Manager R&D': 9, 'Manufacturing Director': 10, 'Research Director': 11, 'Research Scientist': 12, 'Sales Executive': 13, 'Sales Representative': 14, 'Senior Developer': 15, 'Senior Manager R&D': 16, 'Technical Architect': 17, 'Technical Lead': 18}
Encoded BusinessTravelFrequency : {'Non-Travel': 0, 'Travel_Frequently': 1, 'Travel_Rarely': 2}
Encoded OverTime : {'No': 0, 'Yes': 1}
Encoded Attrition : {'No': 0, 'Yes': 1}

## Feature Engineering Decisions
### Why Label Encoding (not One-Hot Encoding)?
* Tree-based models like Random Forest handle label-encoded 
ordinal features well. One-Hot Encoding would expand 26 
features to 50+, adding noise without benefit. so I choose Label Encoding
### Why No PCA?
* PCA reduces interpretability — since the  goal is to explain 
predictions to HR stakeholders, I kept all original features. 
SHAP was used instead for explainability.

In [17]:
# Outlier Detection 
print('='*55)
print('Outlier Detection') 
print('='*55) 
numerical_features = [
    'Age','DistanceFromHome','EmpHourlyRate','NumCompaniesWorked',
    'EmpLastSalaryHikePercent','TotalWorkExperienceInYears','TrainingTimesLastYear',
    'ExperienceYearsAtThisCompany','ExperienceYearsInCurrentRole','YearsSinceLastPromotion',
    'YearsSinceLastPromotion','YearsWithCurrManager'
]
outlier_summary = [] 
for col in numerical_features:
    Q1 = df_encoded[col].quantile(0.25)
    Q3 = df_encoded[col].quantile(0.75) 
    IQR = Q3 - Q1 
    lower = Q1 - 1.5 * IQR 
    upper = Q3 + 1.5 * IQR 
    n_outliers = ((df_encoded[col] < lower) | (df_encoded[col] > upper)) .sum() 
    outlier_summary.append({
        'Feature':col,
        'Q1' : round(Q1, 2), 
        'Q3' : round(Q3,2),
        'Lower_Bound':round(lower,2),
        'Upper_Bound':round(upper,2) ,
        'Outlier_Count':n_outliers,
        'Outlier_%':round(n_outliers / len(df_encoded) * 100,2)
    })
outlier_df = pd.DataFrame(outlier_summary) 
print(outlier_df[outlier_df['Outlier_Count'] > 0].to_string(index=False)) 
print(f'\nTotal Columns with outliers: {(outlier_df['Outlier_Count'] > 0).sum()}')

=======================================================
Outlier Detection
=======================================================
                     Feature  Q1   Q3  Lower_Bound  Upper_Bound  Outlier_Count  Outlier_%
          NumCompaniesWorked 1.0  4.0         -3.5          8.5             39       3.25
  TotalWorkExperienceInYears 6.0 15.0         -7.5         28.5             51       4.25
       TrainingTimesLastYear 2.0  3.0          0.5          4.5            188      15.67
ExperienceYearsAtThisCompany 3.0 10.0         -7.5         20.5             56       4.67
ExperienceYearsInCurrentRole 2.0  7.0         -5.5         14.5             16       1.33
     YearsSinceLastPromotion 0.0  3.0         -4.5          7.5             88       7.33
     YearsSinceLastPromotion 0.0  3.0         -4.5          7.5             88       7.33
        YearsWithCurrManager 2.0  7.0         -5.5         14.5             11       0.92

Total Columns with outliers: 8

## Winsorization ##

In [18]:
# Outlier Capping 
df_capped = df_encoded.copy() 
cap_cols = [
    'NumCompaniesWorked','TotalWorkExperienceInYears',
    'YearsSinceLastPromotion','ExperienceYearsAtThisCompany',
    'ExperienceYearsInCurrentRole','YearsWithCurrManager'
]
for col in cap_cols:
    Q1 = df_capped[col].quantile(0.25) 
    Q3 = df_capped[col].quantile(0.75) 
    IQR = Q3 - Q1 
    lower = Q1- 1.5*IQR 
    upper = Q3 + 1.5 * IQR 
    before = df_capped[col].describe()[['min','max']] 
    df_capped[col] = df_capped[col].clip(lower = lower, upper = upper)
    after = df_capped[col].describe()[['min','max']] 
    print(f'{col:<40} Before: {before.values} -> After: {after.values}') 
    print('\n Outlier Capping Complete')

NumCompaniesWorked                       Before: [0. 9.] -> After: [0.  8.5]

 Outlier Capping Complete
TotalWorkExperienceInYears               Before: [ 0. 40.] -> After: [ 0.  28.5]

 Outlier Capping Complete
YearsSinceLastPromotion                  Before: [ 0. 15.] -> After: [0.  7.5]

 Outlier Capping Complete
ExperienceYearsAtThisCompany             Before: [ 0. 40.] -> After: [ 0.  20.5]

 Outlier Capping Complete
ExperienceYearsInCurrentRole             Before: [ 0. 18.] -> After: [ 0.  14.5]

 Outlier Capping Complete
YearsWithCurrManager                     Before: [ 0. 17.] -> After: [ 0.  14.5]

 Outlier Capping Complete

### Outlier Treatment
* IQR-based capping applied to numerical columns to prevent 
extreme values from skewing the model, without losing records.

In [19]:
# Check for leakage in Attrition
attrition_pref = data.groupby('Attrition')['PerformanceRating'].value_counts(normalize=True).unstack() 
print('PerformanceRating distribution by attrition status:') 
print(attrition_pref.round(3)) 
from scipy.stats import chi2_contingency 
ct = pd.crosstab(data['Attrition'],data['PerformanceRating']) 
chi2, p, dof, expected = chi2_contingency(ct) 
print(f'\nChi-Square test: chi2 = {chi2:.3f},p-value={p:.4f}') 
if p < 0.05:
    print('Attrition is significantly associated with performance Rating') 
    print('Consider training two models: onw with Attrition, one without') 
else:
    print('Attrition shows no significant association- safe to include')

PerformanceRating distribution by attrition status:
PerformanceRating      2      3      4
Attrition
No                 0.155  0.734  0.112
Yes                0.202  0.697  0.101

Chi-Square test: chi2 = 2.567,p-value=0.2771
Attrition shows no significant association- safe to include

In [20]:
# Drop ID column 
df_model = df_encoded.drop(columns=['EmpNumber']) 
print(f'Shape after dropping EmpNumber:{df_model.shape}') 
print(f'Features: {df_model.shape[1] -1}|Target:PerformanceRating')

Shape after dropping EmpNumber:(1200, 27)
Features: 26|Target:PerformanceRating

In [21]:
# Correlation Matrix 
corr_with_target = df_model.corr()['PerformanceRating'].drop('PerformanceRating').sort_values(ascending=False) 
print('Correlation with performanceRating')
print(corr_with_target.round(4))
print('\n----Top 5 Positive Correlations----')
print(corr_with_target.head(5))
print('\n----Top 5 Negative Correlations----')
print(corr_with_target.tail(5))

Correlation with performanceRating
EmpEnvironmentSatisfaction      0.3956
EmpLastSalaryHikePercent        0.3337
EmpWorkLifeBalance              0.1244
OverTime                        0.0502
MaritalStatus                   0.0242
NumCompaniesWorked              0.0210
EmpEducationLevel               0.0205
EducationBackground             0.0056
EmpJobSatisfaction              0.0006
Gender                         -0.0018
TrainingTimesLastYear          -0.0054
EmpJobInvolvement              -0.0105
EmpRelationshipSatisfaction    -0.0195
BusinessTravelFrequency        -0.0310
Attrition                      -0.0398
Age                            -0.0402
EmpHourlyRate                  -0.0431
DistanceFromHome               -0.0461
TotalWorkExperienceInYears     -0.0681
EmpJobLevel                    -0.0766
EmpJobRole                     -0.0962
ExperienceYearsAtThisCompany   -0.1116
YearsWithCurrManager           -0.1223
ExperienceYearsInCurrentRole   -0.1476
EmpDepartment                  -0.1626
YearsSinceLastPromotion        -0.1676
Name: PerformanceRating, dtype: float64

----Top 5 Positive Correlations----
EmpEnvironmentSatisfaction    0.395561
EmpLastSalaryHikePercent      0.333722
EmpWorkLifeBalance            0.124429
OverTime                      0.050206
MaritalStatus                 0.024172
Name: PerformanceRating, dtype: float64

----Top 5 Negative Correlations----
ExperienceYearsAtThisCompany   -0.111645
YearsWithCurrManager           -0.122313
ExperienceYearsInCurrentRole   -0.147638
EmpDepartment                  -0.162615
YearsSinceLastPromotion        -0.167629
Name: PerformanceRating, dtype: float64

## Save the Processed Model ##

In [23]:
import sys
sys.path.append(r'C:\Users\Lenovo\Downloads\Employee Performance')
from config import CLEANED

In [ ]:
df_model = df_capped.drop(columns=['EmpNumber'])
df_model.to_csv(CLEANED, index=False)   # ← index=False belongs HERE
print(f'Cleaned Dataset saved to: {CLEANED}')
print(f'Shape: {df_model.shape}')
print(f'Columns: {df_model.columns.tolist()}')

Cleaned Dataset saved to: C:\Users\Lenovo\Downloads\Employee Performance\data\processed\Employee_Cleaned.csv
Shape: (1200, 27)
Columns: ['Age', 'Gender', 'EducationBackground', 'MaritalStatus', 'EmpDepartment', 'EmpJobRole', 'BusinessTravelFrequency', 'DistanceFromHome', 'EmpEducationLevel', 'EmpEnvironmentSatisfaction', 'EmpHourlyRate', 'EmpJobInvolvement', 'EmpJobLevel', 'EmpJobSatisfaction', 'NumCompaniesWorked', 'OverTime', 'EmpLastSalaryHikePercent', 'EmpRelationshipSatisfaction', 'TotalWorkExperienceInYears', 'TrainingTimesLastYear', 'EmpWorkLifeBalance', 'ExperienceYearsAtThisCompany', 'ExperienceYearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager', 'Attrition', 'PerformanceRating']

## Summary ##


| Steps | Result |
|------|--------|
| Total Records | 1,200 employees |
| Total Features | 26 (+ 1 target) |
| Missing Values | 0 |
| Duplicate Rows | 0 |
| Categorical Encoded | Gender, Department, Education, Job Role, etc. |
| ID Column Dropped | EmpNumber |
| Output File | processed.csv` |

**Next Step:**
Run 'data_exploratory_analysis.ipynb'

## Conclusison ##

**Notebook-1 Complete** 
* Loaded raw INX_Employee_Data.xlsx (1200 rows, 28 columns) 
* Removed duplicates and handled missing values.
* Label Encoded 8 categorical columns 
* Output : Employee_Cleaned.csv( 1200 rows, 27 columns)